### ISSUE TITLE
Stuck on Car Info

### ISSUE THREAD

**Issue by Inervo** [Snaggly/KSW-ToolKit#15]
Hi,

I've just installed ksw toolkit for the first time today, and installed the service from the tool.

Once the service started, I click on "Car Info", and the screen changed to the car original screen info.
But I don't have any controller (my car - bmw Z4 e85 - isn't equipped with a control system), and I'm now stuck on car Info, and I don't know how to revert back.
I've tried rebooting, and the system start ksw toolkit and switch to car info again 😭😭

If you have any idea how to cancel this, or block ksw toolkit to start, I would love it, because I can't use the original screen info from my car..

**Comment by Snaggly** [comment]
Hello,
is your Android touch screen? If yes can you tap on the screen to switch back?

**Comment by Inervo** [comment]
Thanks for getting back to em so quickly:)

Indeed, it's a touchscreen, and that's how I usually get back to android once on car info.

But on this case, it doesn't work, and I don't know of any other way to exist car info

**Comment by Inervo** [comment]
Do you maybe know of a way to kill ksw toolkit ?
Or to reset the whole system at worst ?

**Comment by Snaggly** [comment]
If tapping your screen does not switch anything back, I suspect the MCU reporting false data preventing any system switch. You can try to factory reset the Android to start from a fresh Android. Check here how to do a full OTA Recovery Installation: https://f30.bimmerpost.com/forums/showthread.php?s=cf74137a853f849ef8d620182b9467da&t=1699764

If you are able to connect via adb from a secondary device you could force a screen switch by writing couple bytes to the MCU. On shell you could accomplish that by:
```echo -n \\xf2\\x0\\x69\\x2\\x12\\x1\\x81 > /dev/ttyMSM1```
or if you have an Android 11 with SD625:
```echo -n \\xf2\\x0\\x69\\x2\\x12\\x1\\x81 > /dev/ttyHS1```
or
```echo -n \\xf2\\x0\\x69\\x2\\x12\\x1\\x81 > /dev/ttyHSL1```

That's all I can give for now. Good luck!

**Comment by Inervo** [comment]
Thanks for the update :)

,New info : I've succeeded in switching back to android (I don't know how, there seems to be a very specific area on the screen that launch an app, and exit car info).

I've stopped and uninstalled ksw toolkit as well as the service.
And tried to restart the screen, to check everything was working correctly: it doesn't, same behavior.

So I can now find (painfully and after some time) a way to exit car info, but it still start on it by default (wasn't before), and do know how to revert to normal.
Is a factory reset the only way?

**Comment by Inervo** [comment]
Tried it just now. Still same behavior. But that's not the main issue. This isn't such a problem.

Switching back from car info is still a haste, even though I uninstalled ksw toolkit. 
Should there be something I should have done to uninstall it ?

**Comment by Snaggly** [comment]
Did you also uninstall KSW-ToolKit-Service from your Android settings? Either way it might be advisable to do a full OTA Recovery.

**Comment by Inervo** [comment]
I did yes.

Okay, then I'll do a full OTA recovery :/

Thanks for your time and help. Appreciate it a lot :)

**Comment by Inervo** [comment]
Hello,

Full OTA recovery fixed the problem.
I tried again with a fresh system, the issue appears again. It seems it may be related to this specific screen or car.
Too bad.

Thanks again for your help :)
