### ISSUE TITLE
No Tasker Tasks displayed 

### ISSUE THREAD

**Issue by Starcross** [Snaggly/KSW-ToolKit#19]
Hi, first let me say thanks for a fantastic app. It has fixed many limitations and opened up so many customisation possibilities. 

I wanted to take advantage of the support for Tasker. I installed Tasker and added a task, but when attempting to link a task to a button, no tasks are listed.

![IMG_20240107_161341](https://github.com/Snaggly/KSW-ToolKit/assets/8641396/7c587abf-76bd-4c22-b4db-a9c6594aadc5)

Do I need to do anything else to make the task visible to the app? I have the latest app release (1.2) and service (1.2.2).

**Comment by Snaggly** [comment]
Hello,
afair it should be set up automatically. This feature was developed by another developer, whom I seem to have lost contact to. Unfortunately I am not familiar with how this works, nor do I have the means to test and maintain this on my own. That is why I cannot continue to support this, I'm afraid.

**Comment by surfatwork** [comment]
You need to enable Misc / Allow External Access under preferences in Tasker, and give ksw permissions to run tasker tasks (under android settings->apps->ksw toolkit->permissions->additional permissions). I allowed both ksw and lsw service to do this - I dont know if both need it though.

**Comment by Starcross** [comment]
@surfatwork That was it thank you! 

I just had to 'Allow External Access' in Tasker, and from there was prompted to enable an app permission granting KSW Toolkit access to Tasker. This enabled the list of tasks to appear.
