### ISSUE TITLE
When turning the knob in zlink it goes more than one Titel at a time.

### ISSUE THREAD

**Issue by 3lack5ky** [Snaggly/KSW-ToolKit#8]
I enabled KSW Toolkit and set all button inputs to default, then I launched zlink and let it connect. If I turn the knob, to browse my music I doesn’t go from one Titel to the next, instead it goes one full page down or up. Same on the homescreen of zlink. But in the menus of ksw it works as normal.

**Comment by 3lack5ky** [comment]
Looks like zlink is controlled by left and right, but turning the knob is up and down as default. I tried changing it, but then i got problems with ID7 launcher (homescreen). How about an option to disable remapping the buttons or turning the knob is turning the knob instead of up and down or tilt left and right?

**Comment by Snaggly** [comment]
Hello,
what Version of KSW-ToolKit and ZLINK do you have installed? Also in ZLINK are you using Android Auto or CarPlay?

**Comment by 3lack5ky** [comment]
KSW-ToolKit 1.0
KSW-ToolKit Service 1.0.2
ZLINK 5.2.68
I´m using CarPlay

**Comment by Snaggly** [comment]
The version of the KSW-TK Service you have did only really support up to ZLINK 4.  ZLINK 5 came with a different way to handle input commands, which I implemented in this https://github.com/Snaggly/KSW-ToolKit-Service/commit/1f07fa563f29d536c28623cbe298a23d11ccc4b5 commit. 

If you like you can test a more up to date build, which I'm planning on releasing as the new v1.1 update if I don't find more major breakages: https://drive.google.com/file/d/1v7ojlbPBPJZjUxIwQGAgl2oYA6Np_F6i/view?usp=sharing
When you test this out, let me know if it fixed your issue, thank you!

**Comment by 3lack5ky** [comment]
Thanks, I will test it and let you know if there are any issues or if everything works fine. :)

**Comment by 3lack5ky** [comment]
I´ve now tested the new version for 2 days and I only found one thing, thats different from the standard controlls. If I´m in Carplay and start playing music, I can switch songs by tilting the knob to the left and right, but with ksw toolkit on this is not possible. I kow, I could change tilting to skip song, but then it also would change on all other apps. Is it possible to implement this?
Everything else is working perfectly. :)
