### ISSUE TITLE
Some changes

### ISSUE THREAD

**Issue by itvitacredit** [Snaggly/KSW-ToolKit#9]
In reverse, the camera does not turn on.

Switching on the OEM radio and Android. To use OEM Radio and Android Map (Waze).
When I turn on radio, and then I switch to android, the sound goes to android.

Voice button on steering, I set it to google assistant, but BMW assistant turns on too.

Can't bind Mode button on steering.

Long Press buttons there is no Long Media, Long Map, Long Back, Long Options....

etc...
I use for binding APPS
Waze, Youtube, Assistant, AIMP (Player), HD VideoBOX (Films...), Chrome

**Comment by Snaggly** [comment]
1- Do you have Media-Btn-Hack turned on? If yes, the oem screen will not be automatically triggered when you go into reverse. You can bind any other button on your iDirve (the option button for example) to manually switch to the OEM screen when you're reversing.
2- Do you have automatic aux switching enabled in factory settings?
3- Your MCU does not block the button press from your Head Unit, but you can fully disable BMW's voice assist by coding SVS to "nicht_aktiv" in your HU. This can be done with BimmerCode or E-Sys.
4- Did you enable the Mode function key on your Factory settings? MCU will not pick up any signal if it's not turned on or if it's supported. If you have Media-Btn-Hack turned on, both Mode on steering, radio and iDrive button will be the same.
5- MCU mostly only picks up when you release a button. You can check in 'MCU LISTENER' what your MCU will pick up or not.

**Comment by itvitacredit** [comment]
1. What is Media-Btn-**Hack**? where can I change it?
2. Aux change to automatic
3. Ok
4. ok
5. ok.

Thank You
